version: "3.7"

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containerwill
    restart: always
    ports:
      - 8050:80


  databaseWilliam:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 2181336
      POSTGRES_USER: williamdel
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata: